language: ruby

# https://github.com/discourse/mini_racer#travis-ci
sudo: required
dist: trusty

addons:
  chrome: stable

git:
  submodules: false

branches:
  only:
  - master
  - /^.*-stable$/
  - /^.*ci-check$/

cache:
  bundler: true
  directories:
    - /home/travis/.nvm/
    - smoke_test_opal_rspec
    - node_modules

matrix:
  fast_finish: true

  include:
    - rvm: 2.5
      env: RUN=mspec_opal_chrome

    - rvm: 2.5
      env: RUN=mspec_ruby_chrome

    - rvm: 2.5.3
      env: RUN=mspec_opal_owl

    - rvm: 2.5.3
      env: RUN=mspec_ruby_owl

    # - rvm: 2.5
    #   env:
    #     - RUN=browser_test
    #     - SAUCE_USERNAME=elia
    #     # SAUCE_ACCESS_KEY:
    #     - secure: GT13SjzU8vmqKIyY2LAXje+ndqevTsX/w71JkZHRLTrDUl0qcIod7xsfahbzGt2gOZPYZUkKiVaPoUenhc/YeJ2jTJVHeHY9UEl2II+3tOtuvp2jLadA//aBbsB6/09d7lIZMzpa93TL2R/SncPxugYW9v2o8o8Lwd2iIzowT/g=

    - rvm: 2.5
      env: RUN=lint

    - rvm: 2.5
      env: RUN=mspec_opal_nodejs

    - rvm: 2.5
      env: RUN=mspec_ruby_nodejs TZ="/usr/share/zoneinfo/Pacific/Fiji"

    - rvm: 2.5
      env: RUN=minitest

    - rvm: 2.5
      env: RUN=rspec RACK_VERSION='~> 2.0' CHECK_COVERAGE=true

    - rvm: 2.5
      env: RUN=smoke_test

    - rvm: ruby-head
      env: RUN=rspec

    - rvm: 2.4
      env: RUN=rspec RACK_VERSION='~> 2.0'

    - rvm: 2.3
      env: RUN=rspec

    - rvm: 2.6
      env: RUN=rspec

    - rvm: truffleruby
      env: RUN=rspec

    - rvm: jruby-9.2
      env:
        - RUN=rspec
        - JRUBY_OPTS=--dev

    - rvm: jruby-head
      env:
        - RUN=rspec
        - JRUBY_OPTS=--dev

  allow_failures:
    - rvm: ruby-head
    - rvm: jruby-head
    - rvm: truffleruby
    - env: RUN=smoke_test
    - env: RUN=mspec_ruby_owl

before_install:
  # Keep track of which version of node we're running the specs against
  - bin/git-submodule-fast-install
  - node -v
  - npm install
  - export PATH="node_modules/.bin:$PATH"
  - bundle config without doc
  - which google-chrome-stable
  - google-chrome-stable --version
  - export RUBYOPT=-w
  # Workaround from https://github.com/travis-ci/travis-ci/issues/9024#issuecomment-356282802
  - sudo chown root /opt/google/chrome/chrome-sandbox
  - sudo chmod 4755 /opt/google/chrome/chrome-sandbox

script:
  - "bundle exec rake $RUN"
